# Generated by Django 6.1.1 on 2026-10-06 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_preferences(apps, schema_editor):
    user_app, user_model = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(user_app, user_model)
    UserPreferences = apps.get_model("expenses", "UserPreferences")
    database = schema_editor.connection.alias
    UserPreferences.objects.using(database).bulk_create(
        [UserPreferences(user_id=user_id, currency="EUR") for user_id in User.objects.using(database).values_list("id", flat=True)]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_translate_default_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('EUR', 'Euro (EUR)'), ('USD', 'US dollar (USD)'), ('GBP', 'British pound (GBP)'), ('PLN', 'Polish złoty (PLN)'), ('CHF', 'Swiss franc (CHF)'), ('CAD', 'Canadian dollar (CAD)'), ('AUD', 'Australian dollar (AUD)'), ('JPY', 'Japanese yen (JPY)'), ('INR', 'Indian rupee (INR)'), ('SEK', 'Swedish krona (SEK)')], default='EUR', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='money_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_default_preferences, migrations.RunPython.noop),
    ]
