# Generated by Django 6.1.1 on 2026-10-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_savingsgoal_goalcontribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('uk', 'Українська'), ('pl', 'Polski'), ('de', 'Deutsch')], default='en', max_length=2),
        ),
    ]
